global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  web:
    address: :80
  https:
    address: :443
providers:
  docker:
      exposedByDefault: false
#accessLog: {}
metrics:
  prometheus: {}
api:
  dashboard: true
  #  insecure: true
log:
  level: INFO
certificatesResolvers:
  default:
    acme:
      email: nomorsad.poubelle@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web
