global:
  scrape_interval: 30s

    #remote_write:
    #- url: "http://promscale:9201/write"
    #remote_read:
    #  - url: "http://promscale:9201/read"
    #    read_recent: true

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: kimsufi
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: traefik
    static_configs:
      - targets: ['traefik:8080']
  - job_name: fail2ban
    static_configs:
      - targets: ['fail2ban_exporter:9191']
  - job_name: jellyfin
    static_configs:
      - targets: ['jellyfin:8096']

